### ISSUE TITLE
"Cutting" fences

### ISSUE THREAD

**Issue by lramati** [tyrope/fencing#16]
With PvP / adventure maps in mind, a way to cut fences without dropping the item that would be considerably faster than breaking it down. You mentioned adventure map checkpoints in IRC, I was thinking more compound infiltration in custom PvP maps.
Cutting a fence would allow you to move through it's block, but probably shouldn't drop any resources and result in two fence posts dropping when broken instead of the whole fence.

**Comment by tyrope** [comment]
- [x] New block: cut fence. - Uncraftable except by using shears on in-world fence block. - has no collision box. - drops 2 fence posts when broken.
- [x] Cut fences with shears (harder fences either need several clicks, or has chance to not break. Feedback welcome) Either way the chance/amount of clicks will be configurable. configurable 'drop middle part'

Marked as 'future' for now. ETA: 0.4

**Comment by tyrope** [comment]
https://github.com/tyrope/fencing/commit/dd6f183afd1bc699495c1f91670124043398393b adds the first of the two features completely, though drops a cut fence instead of 2 fence posts.
It also adds the second feature, though not completely. every fence takes 1 durability off the shears and never drops the middle part.

**Comment by tyrope** [comment]
https://github.com/tyrope/fencing/commit/12b974f84440eb44f484991ec0570c89343708e8 finalizes the fence cutting bits by dropping the items IF the config is set to do so (defaults to true)
