### ISSUE TITLE
Animal AI

### ISSUE THREAD

**Issue by Epik-** [tyrope/fencing#26]
`repo owner edit:` Split into two issues for easier tracking. Section about cables can be found in #27

I have found two bugs:
1- Mobs don't consider the fences as actual fences in their AI, they just continue walking into them, and they don't run away if shocked by electricity or cut my barbed wire.
[snip]

Sorry if I did this wrong, just created this account and have never used github before.

**Comment by tyrope** [comment]
Thank you for reporting these bugs. For easier tracking I've split them up.

**Comment by tyrope** [comment]
@Epik- Now that I've started to convert to 1.7, could you provide more details on this? Specifically, what you expect a mob doing when they hit the fence. I don't actually modify any AI.

**Comment by alucas** [comment]
To be simple, there is two steps in the AI movement : 
- The pathfinder
- The movement

The first step look for a walk-able path, but do not check en blocks hit boxs. it have his own blocks exception (Doors, Water, Lava, Fences, ...). If a path is found, the entity is moved, and here the hit boxs are tested. So your blocks with custom height are not present in the pathfinder exceptions, they are considered like a normal block, so the entities think they can jump on. That's why they jump like idiot. They stop jumping when the stuck timer run out.

The pathfinder is really messy, and not instrumented by forge, so I don't think there is a solution for now.

``` java
// net.minecraft.pathfinding.Pathfinder : 341
if (renderType == 11 || block == Blocks.fence_gate || renderType == 32)
{
    return -3;
}
```

**Comment by tyrope** [comment]
Marked wontfix until Forge fixes it... I might at some point look into submitting a PR.

**Comment by alucas** [comment]
Fixed.
